#!/usr/bin/env bash

# can not name this file just bash as that would cause an infinite loop by direnv, trying to run this file by "bash"

set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$DIR")"

source "${DIR}/_tty.sh"

if [ "$(docker compose ps phpnginx | grep --count Up)" -gt 0 ]; then
	docker_compose_exec \
		--workdir="/src${PWD:${#PROJECT_ROOT}}" \
		--user=application \
		phpnginx bash "$@"
else
	docker_compose_run \
		--entrypoint=/bin/bash \
		--workdir="/src${PWD:${#PROJECT_ROOT}}" \
		--user=application \
		phpnginx "$@"
fi
