#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$DIR")"
# some value to avoid 'invalid environment variable: ' docker compose error
APP_ENV_DEFINITION='EMPTY_NOTHINGNESS'
if [ -n "${APP_ENV:-}" ]; then
  APP_ENV_DEFINITION="APP_ENV=${APP_ENV}"
fi

source "${DIR}/_tty.sh"

if [ "$(docker compose ps phpnginx | grep --count Up)" -gt 0 ]; then
	docker_compose_exec \
		--workdir="/src${PWD:${#PROJECT_ROOT}}" \
		--user=application \
		--env="${APP_ENV_DEFINITION}" \
		phpnginx php "$@"
else
    # without --entrypoint=/usr/local/bin/php as that may break loading of php.ini
	docker_compose_run \
		--entrypoint=php \
		--workdir="/src${PWD:${#PROJECT_ROOT}}" \
		--user=application \
		--env="${APP_ENV_DEFINITION}" \
		phpnginx "$@"
fi
